require: rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Naming/MethodParameterName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
