require: rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Gemspec/RequireMFA:
  Severity: info

Naming/MethodParameterName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
