name: Merge Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7.x, 2.6.x, 2.5.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: |
          gem install bundler
          bundle install
      - run: rake test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: |
          gem install bundler
          bundle install
      - run: rake rubocop

  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7.x, 2.6.x, 2.5.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: |
          gem install bundler
          bundle install
      - run: rake test:integration

